apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-app-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/<gcp-project-id>/secrets/api-app-database-connection-string/versions/latest"
        path: "api-app-database-connection-string"
  secretObjects:
    - data:
      - key: DB
        objectName: api-app-database-connection-string
      secretName: api-app-secrets
      type: Opaque